name: CI Demo

on:
  push:
    branches: [ "main" ]   # Run pipeline when code is pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Hello Script
        run: echo "Hello, CI/CD is working 🎉"
